---
- name: config_php | installing php5
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php5
    - php5-cli
    - php5-fpm
  when: ansible_os_family == "Debian"

- name: config_php | configuring php.ini
  template:
    src: "etc/php5/fpm/php.ini.j2"
    dest: "/etc/php5/fpm/php.ini"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart php5-fpm
  when: ansible_os_family == "Debian"
